sudo: required
services:
  - docker

before_install:
  - docker build -t dlrschris1193/react-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run dlrschris1193/react-tests npm run test -- --watchAll=false

after_success:
  - docker build -t dlrchris1193/multi-client ./client
  - docker build -t dlrchris1193/multi-nginx ./nginx
  - docker build -t dlrchris1193/multi-server ./server
  - docker build -t dlrchris1193/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dlrchris1193/multi-client
  - docker push dlrchris1193/multi-nginx
  - docker push dlrchris1193/multi-server
  - docker push dlrchris1193/multi-worker
